import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeIndianRupee, Bot, CircleCheck, CloudCog, FileSearch, HandCoins, PackageSearch, Radar, Scale, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import dashboard from "../assets/thirdnetra-intelligence-dashboard.jpg";
import { ButtonLink } from "../components/button";
import { SiteLayout } from "../components/site-layout";
import { RoiCalculator } from "../components/roi-calculator";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "eCommerce Reconciliation Services | ThirdNetra" }, { name: "description", content: "Recover hidden revenue with courier billing audits, COD reconciliation, weight dispute recovery, and logistics intelligence." }, { property: "og:title", content: "Stop Losing Money to Hidden eCommerce Billing Errors" }, { property: "og:description", content: "ThirdNetra detects, disputes, and recovers revenue leakage for Indian eCommerce sellers." }, { property: "og:url", content: "/" }], links: [{ rel: "canonical", href: "/" }] }), component: Home });

const services = [[FileSearch,"Financial Reconciliation","Match invoices, remittances, credits, and payouts."],[Scale,"Courier Billing Audit","Review freight, weight, and surcharge charges."],[HandCoins,"COD Recovery","Track delayed or missing COD remittances."],[ShieldCheck,"Dispute Management","End-to-end dispute filing and escalation."],[BadgeIndianRupee,"Waiver Recovery","Negotiate and recover unjustified charges."],[Radar,"Logistics Intelligence","Analytics dashboards and actionable insights."]] as const;
const steps = ["Connect data sources","AI detects anomalies","Experts validate claims","Disputes raised","Revenue recovered"];
const studies = [["₹18L","Seller saved annually","Courier overcharges and COD discrepancies recovered."],["8%","Leakage reduction","Automated reconciliation for a fast-growing D2C brand."],["₹42L","Marketplace recovery","Weight dispute resolution and waiver recovery."]];

function Home() { return <SiteLayout>
  <section className="relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-40"/><div className="relative mx-auto grid max-w-7xl gap-16 px-5 pb-20 pt-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-cyan"><Sparkles className="size-3.5"/> eCommerce Finance & Logistics Intelligence</div><h1 className="mt-7 font-display text-5xl font-semibold leading-[1.03] tracking-[-.045em] text-foreground sm:text-6xl lg:text-7xl">Stop losing money to <span className="text-gradient">hidden billing errors.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">ThirdNetra continuously audits your logistics and platform data to uncover overcharges, COD discrepancies, weight disputes, missing refunds, and revenue leakages.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink to="/contact">Get free audit <ArrowRight className="ml-2 size-4"/></ButtonLink><ButtonLink to="/contact" variant="secondary">Schedule consultation</ButtonLink></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground">{["Zero-risk discovery","Expert-validated claims","India-focused recovery"].map(x=><span key={x} className="flex items-center gap-2"><CircleCheck className="size-4 text-success"/>{x}</span>)}</div></div><div className="relative"><div className="absolute -inset-10 rounded-full bg-primary/15 blur-3xl"/><div className="relative animate-float overflow-hidden rounded-2xl border border-primary/30 bg-card p-2 shadow-[var(--shadow-panel)]"><img src={dashboard} alt="ThirdNetra revenue leakage intelligence dashboard" width={1536} height={1024} className="aspect-[3/2] w-full rounded-xl object-cover"/><div className="animate-scan absolute inset-x-5 top-10 h-px bg-cyan"/></div><div className="absolute -bottom-6 -left-4 rounded-2xl border border-primary/30 bg-background/90 p-4 shadow-[var(--shadow-panel)] backdrop-blur"><p className="text-xs text-muted-foreground">Recovery identified</p><p className="mt-1 font-display text-2xl font-semibold text-success">₹12,48,620</p></div></div></div></section>
  <section className="border-y border-border bg-surface"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px bg-border md:grid-cols-4">{[["3–12%","Revenue at risk"],["6+","Leakage categories"],["100%","Claim validation"],["End-to-end","Dispute ownership"]].map(([n,l])=><div key={l} className="bg-surface px-5 py-8 text-center"><p className="font-display text-3xl font-semibold text-foreground">{n}</p><p className="mt-1 text-xs uppercase tracking-widest text-muted-foreground">{l}</p></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Why ThirdNetra</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight text-foreground">Your third eye for eCommerce profitability.</h2><p className="mt-5 leading-7 text-muted-foreground">Visibility is not enough. ThirdNetra combines intelligent detection with expert action to turn discrepancies into recovered cash.</p></div><div className="grid gap-4 sm:grid-cols-3">{[[PackageSearch,"Detect","Identify hidden billing errors automatically."],[CloudCog,"Resolve","Raise and coordinate disputes with platforms."],[TrendingUp,"Recover","Secure waivers, credits, and revenue."]].map(([Icon,t,c],i)=><article key={String(t)} className="rounded-2xl border border-border bg-card p-6 transition hover:-translate-y-1 hover:border-primary/45"><span className="text-xs text-primary">0{i+1}</span><Icon className="mt-8 size-7 text-cyan"/><h3 className="mt-5 font-display text-xl font-semibold text-foreground">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{c}</p></article>)}</div></div></section>
  <section className="bg-surface py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Managed recovery services</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground">Every leak. One recovery layer.</h2></div><Link to="/services" className="flex items-center gap-2 text-sm font-semibold text-cyan">Explore all services <ArrowRight className="size-4"/></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,t,c])=><article key={t} className="rounded-2xl border border-border bg-card p-6"><Icon className="size-6 text-primary"/><h3 className="mt-8 font-display text-lg font-semibold text-foreground">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{c}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="eyebrow">How it works</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground">From raw data to recovered revenue.</h2></div><div className="relative mt-14 grid gap-4 md:grid-cols-5"><div className="absolute left-[10%] right-[10%] top-7 hidden h-px bg-gradient-to-r from-primary via-cyan to-success md:block"/>{steps.map((s,i)=><div key={s} className="relative text-center"><span className="relative z-10 mx-auto grid size-14 place-items-center rounded-full border border-primary/40 bg-background font-display font-semibold text-primary">{i+1}</span><p className="mt-5 text-sm font-semibold text-foreground">{s}</p></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><RoiCalculator /></section>
  <section className="border-y border-border bg-surface py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="eyebrow">Verified outcomes</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-semibold text-foreground">Recovery stories written in rupees.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{studies.map(([n,t,c])=><article key={n} className="rounded-2xl border border-border bg-card p-7"><p className="font-display text-4xl font-semibold text-primary">{n}</p><h3 className="mt-7 font-display text-xl font-semibold text-foreground">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{c}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><div><p className="eyebrow">Built for commerce operators</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground">Trusted by the people accountable for every rupee.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[["D2C Founder","“We finally know where every logistics rupee goes—and what to challenge.”"],["Amazon Seller","“ThirdNetra found billing patterns our team had accepted for months.”"],["Operations Head","“Disputes moved from spreadsheets to a disciplined recovery workflow.”"],["Finance Manager","“Payout and COD reconciliation is now clear, fast, and auditable.”"]].map(([r,q])=><blockquote key={r} className="rounded-2xl border border-border bg-card p-5"><p className="text-sm leading-6 text-foreground">{q}</p><footer className="mt-5 text-xs font-semibold uppercase tracking-widest text-cyan">{r}</footer></blockquote>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="overflow-hidden rounded-3xl border border-primary/30 bg-radiance px-6 py-14 text-center sm:px-12"><Bot className="mx-auto size-9 text-cyan"/><h2 className="mx-auto mt-5 max-w-2xl font-display text-4xl font-semibold text-foreground">Put a recovery team behind every order.</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Start with a confidential revenue leakage audit. We’ll show you where to look—and what may be recoverable.</p><ButtonLink to="/contact" className="mt-8">Get your free audit <ArrowRight className="ml-2 size-4"/></ButtonLink></div></section>
 </SiteLayout> }
