import { useState, type FormEvent } from "react";
import { CheckCircle2 } from "lucide-react";
import { buttonClass } from "./button";

export function LeadForm() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  if (sent) return <div className="rounded-3xl border border-primary/30 bg-primary/10 p-10 text-center"><CheckCircle2 className="mx-auto size-12 text-primary"/><h2 className="mt-5 font-display text-2xl font-semibold text-foreground">Your audit request is in.</h2><p className="mt-2 text-muted-foreground">A ThirdNetra recovery specialist will contact you shortly.</p></div>;
  const field = "w-full rounded-xl border border-input bg-secondary px-4 py-3 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20";
  return <form onSubmit={submit} className="rounded-3xl border border-border bg-card p-6 shadow-[var(--shadow-panel)] sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-muted-foreground">Name<input className={`${field} mt-2`} name="name" required maxLength={100} /></label><label className="text-sm text-muted-foreground">Company<input className={`${field} mt-2`} name="company" required maxLength={120} /></label><label className="text-sm text-muted-foreground">Monthly order volume<select className={`${field} mt-2`} name="volume" required defaultValue=""><option value="" disabled>Select range</option><option>Under 5,000</option><option>5,000–25,000</option><option>25,000–100,000</option><option>100,000+</option></select></label><label className="text-sm text-muted-foreground">Work email<input className={`${field} mt-2`} name="email" type="email" required maxLength={255} /></label><label className="text-sm text-muted-foreground sm:col-span-2">Phone number<input className={`${field} mt-2`} name="phone" type="tel" required pattern="[0-9+() -]{8,18}" maxLength={18} /></label><label className="text-sm text-muted-foreground sm:col-span-2">Where do you suspect revenue leakage?<textarea className={`${field} mt-2 min-h-28 resize-y`} name="message" required maxLength={1000} /></label></div><button type="submit" className={`${buttonClass.primary} mt-5 w-full`}>Get your free revenue leakage audit</button><p className="mt-4 text-center text-xs text-muted-foreground">Your business data stays confidential. No spam, ever.</p></form>;
}