import { useMemo, useState } from "react";
import { IndianRupee, TrendingUp } from "lucide-react";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export function RoiCalculator() {
  const [orders, setOrders] = useState(10000);
  const [shipping, setShipping] = useState(85);
  const annualSpend = orders * shipping * 12;
  const recovery = useMemo(() => ({ low: annualSpend * 0.02, high: annualSpend * 0.1 }), [annualSpend]);
  return <div className="grid overflow-hidden rounded-3xl border border-border bg-card lg:grid-cols-2"><div className="p-6 sm:p-10"><p className="eyebrow">Recovery estimator</p><h2 className="mt-4 font-display text-3xl font-semibold tracking-tight text-card-foreground sm:text-4xl">Calculate your hidden opportunity</h2><p className="mt-4 text-muted-foreground">See what a 2–10% recovery range could mean for your logistics spend.</p><div className="mt-9 space-y-7"><label className="block"><span className="flex justify-between text-sm text-muted-foreground"><span>Monthly orders</span><strong className="text-foreground">{orders.toLocaleString("en-IN")}</strong></span><input aria-label="Monthly orders" type="range" min="1000" max="100000" step="1000" value={orders} onChange={(e)=>setOrders(Number(e.target.value))} className="mt-3 w-full accent-primary" /></label><label className="block"><span className="flex justify-between text-sm text-muted-foreground"><span>Average shipping cost</span><strong className="text-foreground">{currency.format(shipping)}</strong></span><input aria-label="Average shipping cost" type="range" min="40" max="300" step="5" value={shipping} onChange={(e)=>setShipping(Number(e.target.value))} className="mt-3 w-full accent-primary" /></label><div className="rounded-2xl border border-border bg-secondary p-4"><span className="text-xs uppercase tracking-widest text-muted-foreground">Annual shipping spend</span><p className="mt-2 font-display text-2xl font-semibold text-foreground">{currency.format(annualSpend)}</p></div></div></div><div className="relative flex flex-col justify-center bg-radiance p-6 sm:p-10"><div className="absolute right-8 top-8 grid size-12 place-items-center rounded-2xl border border-primary/30 bg-primary/10 text-primary"><TrendingUp /></div><p className="text-sm text-muted-foreground">Potential monthly savings</p><p className="mt-2 font-display text-3xl font-semibold text-foreground">{currency.format(recovery.low/12)} – {currency.format(recovery.high/12)}</p><div className="my-7 h-px bg-border"/><p className="text-sm text-muted-foreground">Potential annual recovery</p><p className="mt-2 flex items-center font-display text-4xl font-semibold text-primary sm:text-5xl"><IndianRupee className="mr-1 size-8" />{Math.round(recovery.low).toLocaleString("en-IN")} – {Math.round(recovery.high).toLocaleString("en-IN")}</p><p className="mt-5 text-xs leading-5 text-muted-foreground">Illustrative estimate based on typical leakage patterns. Actual recovery depends on carriers, platforms, contract terms, and data quality.</p></div></div>;
}